export default { 'Active Customer': 'label.customerfact.activecustomer',
  'Ad Media Name': 'label.promotiondimension.admedianame',
  'Ad Type': 'label.promotiondimension.adtype',
  'Annual Income': 'label.customerdimension.annualincome',
  'Annual Shrinkage': 'label.storedimension.annualshrinkage',
  'Average Competitor Price': 'fact.sale.averagecompetitorprice',
  'Average Product Price': 'aatQc0FhgJtQ',
  'Avg In Store Order Value': 'acqffbfYdYI7',
  'Avg Number of Purchase [Avg]': 'aagOaj7WcKFY',
  'Avg Online Order Value': 'adYffgS3dX9a',
  'Avg Sales Revenue Brand': 'aaiv6Ag2b4A3',
  'Avg Time Spent': 'fact.onlinebehaviourfact.avgtimespent',
  'Avg Total Order [Prev Q]': 'abAfjPhXfbPy',
  'Avg Total Order Value': 'aaSfiM4Ygb2A',
  'Avg Total Order Value Activewear': 'aaAf1Y2zboZt',
  'Avg Total Orders [QoQ]': 'aaMfkhiCfjlT',
  'Best Brand Market Customer %': 'abnNUPk9gVlK',
  'BKUP Total Customers [COUNT]': 'aacP1G4yidPv',
  'BKUP Total Loyalty Customers [COUNT]': 'aaFP0ZVIdCvn',
  'Brand $ Market Share %': 'aa6UkVJvbFas',
  'Brand CP': 'label.brand.brandcp',
  'Brand Customer Share %': 'aauwR7bHhrx7',
  'Brand Market Share %': 'aaMPpK5gcfYD',
  'Brand Name': 'label.brand.brandname',
  'Brand Revenue Target': 'fact.targetrevenue.brandrevenuetarget',
  'Brand Revenue Target [SUM]': 'aa691fjkfF7z',
  'Cart Abandonment Rate': 'fact.onlinebehaviourfact.cartabandonmentrate',
  'Category Description': 'label.productdimension.categorydescription',
  'Channel CP': 'label.channel.channelcp',
  'Channel Type': 'label.channel.channeltype',
  City: 'label.salesregion.city',
  Color: 'label.productdimension.color',
  'Copy of Expected Sales (Product Sales + Predicted) [SoS]': 'aabce77Cd00a',
  'Copy of Test of Brand $ Market Share %': 'aac8QSP7gaKj',
  'Coupon Type': 'label.promotiondimension.coupontype',
  'Customer Address': 'label.customerdimension.customeraddress',
  'Customer Age': 'label.customerdimension.customerage',
  'Customer Age Group': 'label.customerdimension.customeragegroup',
  'Customer By Income Bracket %': 'aahTGoATd6gU',
  'Customer City': 'label.customerdimension.customercity',
  'Customer Demographic': 'label.customerdimension.customerdemographic.agegroup',
  'Customer Gender': 'label.customerdimension.customergender',
  'Customer Key': 'label.customerdimension.customerkey',
  'Customer Name': 'label.customerdimension.customername',
  'Customer Region': 'label.customerdimension.customerregion',
  'Customer Segment': 'label.customerdimension.customersegment',
  'Customer Shop Activewear %': 'aaQww99WbGfv',
  'Customer State': 'label.customerdimension.customerstate',
  'Customer Type': 'label.customerdimension.customertype',
  'Deal Size 1': 'label.venderdimension.dealsize',
  'Deal Size 2': 'label.customerdimension.sealsize',
  'Deal Stage': 'label.customerdimension.dealstage',
  Department: 'label.productdimension.department',
  'Diet Type': 'label.productdimension.diettype',
  'Discontinued Flag': 'label.productdimension.discontinuedflag',
  'Display Provider': 'label.promotiondimension.displayprovider',
  'Display Type': 'label.promotiondimension.displaytype',
  'Expected Revenue PO [P Season]': 'aadIEqukbut4',
  'Expected Revenue PO [SoS]': 'aaNJd0Y5hA6h',
  'Expected Revenue PO [SUM]': 'aakrVqIEgyYO',
  'Expected Sales (Product Sales + Predicted) [Prev Q]': 'aahJhZvrecl8',
  'Expected Sales (Product Sales + Predicted) [SoS]': 'aasJhMVEeDkd',
  'Expected Sales (Product Sales + Predicted) [SUM]': 'aavggt5Zfe2U',
  'Fat Content': 'label.productdimension.fatcontent',
  'Financial Service Type': 'label.storedimension.financialservicetype',
  'Floor Plan Type': 'label.storedimension.floorplantype',
  'Foot Traffic': 'label.storedimension.foottraffic',
  'Geo CP': 'label.geo.geocp',
  'Geo Description': 'label.geo.geodescription',
  'Highest Competitor Price': 'fact.sale.highestcompetitorprice',
  'Household Id': 'label.customerdimension.housholdid',
  'Ideal Purchase Goal [SUM]': 'aacrXRE5g5ch',
  'In Store Orders [COUNT]': 'aaceQmZZb9kp',
  'In Store Quantity [SUM]': 'aasdIAqpht4V',
  'In Store Revenue [SUM]': 'aaK9P8Hgibo1',
  'Income Bracket': 'label.customerdimension.incomebracket',
  'Largest Bill Amount': 'label.customerdimension.largestbillamount',
  'Last 12 Months Product Line Revenue %': 'aasxRWC1hUFe',
  'Lower Competitor Price': 'fact.sale.lowercompetitorprice',
  'Loyalty %': 'aakgr73peDnT',
  'Loyalty % [Prev Q]': 'aaogBgeoheE3',
  'Loyalty % [Prev Y]': 'aaMTo6Zrdqa4',
  'Loyalty % QoQ': 'aaGgAIESas9B',
  'Margin %': 'aaWjLNoBeA9w',
  'Marital Status': 'label.customerdimension.maritalstatus',
  'Month Active Flag': 'fact.customerfact.monthactiveflag',
  'Monthly Rent Cost': 'label.storedimension.monthlyrentcost',
  'Net Amount': 'fact.onlinesalesfact.netamount',
  'New Members': 'label.customerfact.newcustomer',
  'Number of Children': 'label.customerdimension.numberofchildren',
  'Number of Employees': 'label.storedimension.numberofemployees',
  'Number of Purchase': 'fact.customerfact.numberofpurchase',
  Occupation: 'label.customerdimension.occupation',
  'Online Cost Amount': 'fact.onlinesalesfact.costamount',
  'Online Gross Profit Amount': 'fact.onlinesalesfact.grossprofitamount',
  'Online Gross Profit Amount [Sum]': 'acfjI6FHiqLX',
  'Online Order ID': 'label.onlinesalesfact.onlineorderid',
  'Online Orders [COUNT]': 'aa0fhE84eES5',
  'Online Payment': 'label.onlinebehaviourfact.onlinepayment',
  'Online Quantity [SUM]': 'aaedIZANhy5F',
  'Online Revenue [SUM]': 'aay9QfXOikF6',
  'Online Sales Amount': 'fact.onlinesalesfact.salesamount',
  'Online Sales Quantity': 'fact.onlinesalesfact.salesquantity',
  'Order Number': 'label.storeordersfact.ordernumber',
  'Order Target Amount': 'fact.storeordertargets.ordertarget',
  'Organic Search Visitor': 'label.onlinebehaviourfact.organicsearchvisitor',
  'Overstock Ceiling': 'fact.storeordersfact.overstockceiling',
  'Package Size': 'label.productdimension.packagesize',
  'Package Type Description': 'label.productdimension.packagetypedescription',
  'Photo Processing Type': 'label.storedimension.photoprocessingtype',
  'POS Transaction Number 1': 'label.onlinesalesfact.postransactionnumber',
  'POS Transaction Number 2': 'label.storesalesfact.postransactionnumber',
  'Predicted Sales Amount': 'fact.predictedsales.predictedsalesamount',
  'Predicted Sales Quantity': 'fact.predictedsales.predictedsalesquantity',
  'Price Reduction Type': 'label.promotiondimension.pricereductiontype',
  'Product Cost': 'fact.sale.productcost',
  'Product Description': 'label.productdimension.productdescrition',
  'Product Gender': 'label.productdimension.gender',
  'Product Key': 'label.productdimension.productkey',
  'Product Key Version': 'label.productdimension.productkeyversion',
  'Product Line': 'label.productdimension.productline',
  'Product Line Image': 'label.productdimension.productimage',
  'Product Price': 'fact.sale.productprice',
  'Product Type': 'label.productdimension.producttype',
  'Product Type CP': 'label.producttype.producttypecp',
  'Product Type Image': 'label.producttype.producttypeimage',
  'Product Version': 'label.productdimension.productversion',
  'Projected Inventory 1': 'fact.inventoryfact.projectedinventory',
  'Projected Inventory 2': 'aamPiEklfpdw',
  'Projected Order Cost': 'fact.storeordersfact.projectedordercost',
  'Projected Quantity Order': 'fact.storeordersfact.projectedquantityorder',
  'Promotion Cost': 'label.promotiondimension.promotioncost',
  'Promotion Key': 'label.promotiondimension.promotionkey',
  'Promotion Media Type': 'label.promotiondimension.promotionmediatype',
  'Promotion Name': 'label.promotiondimension.promotionname',
  'Quantity Delivered': 'fact.storeordersfact.quantitydelivered',
  'Quantity in Stock 1': 'fact.storeordersfact.quantityinstock',
  'Quantity in Stock 2': 'fact.inventoryfact.quantityinstock',
  'Quantity Ordered': 'fact.storeordersfact.quantityordered',
  Region: 'label.salesregion.region',
  'Reorder Level': 'fact.storeordersfact.reorderlevel',
  'Returning Visitor': 'label.onlinebehaviourfact.returningvisitor',
  'Revenue (Orders) [Runsum]': 'aboqyGGQd5Lq',
  'Sales (Purchase) [Runsum]': 'abAqx2LtdVXQ',
  'Sales Region ID': 'label.salesregion.salesregionid',
  'Season Description': 'label.seasons.seasondescription',
  'Seasons CP': 'label.seasons.seasonscp',
  'Sell Thru Rate': 'aaiPhVVFd1oQ',
  'Selling Square Footage': 'label.storedimension.sellingsquarefootage',
  'Shelf Depth': 'label.productdimension.shelfdepth',
  'Shelf Height': 'label.productdimension.shelfheight',
  'Shelf Width': 'label.productdimension.shelfwidth',
  'Ship Amount': 'fact.onlinesalesfact.shipamount',
  'Shipper Name': 'label.storeordersfact.shippername',
  'Shipping Cost': 'fact.storeordersfact.shippingcost',
  Size: 'label.productdimension.size',
  'SKU Number': 'label.productdimension.skunumber',
  State: 'label.salesregion.state',
  'Store Address': 'label.storedimension.storeaddress',
  'Store City': 'label.storedimension.storecity',
  'Store Cost Amount': 'fact.storesalesfact.costamount',
  'Store Gross Profit Amount': 'fact.storesalesfact.grossprofitamount',
  'Store Gross Profit Amount [Sum]': 'adtjJjc4iua8',
  'Store Key': 'label.storedimension.storekey',
  'Store Membership Card': 'label.customerdimension.storemembershipcard',
  'Store Name': 'label.storedimension.storename',
  'Store Number': 'label.storedimension.storenumber',
  'Store Order ID': 'label.storesalesfact.storeorderid',
  'Store Region': 'label.storedimension.storeregion',
  'Store Sales Amount': 'fact.storesalesfact.salesamount',
  'Store Sales Quantity': 'fact.storesalesfact.salesquantity',
  'Store State': 'label.storedimension.storestate',
  'Sub Category CP': 'label.subcategory.subcategorycp',
  'Sub Category Description': 'label.subcategory.subcategorydescription',
  'Sub Category Image': 'label.subcategory.subcategoryimage',
  'Sub Category Revenue Target': 'fact.subcategorytargetrevenue.subcategoryrevenuetarget',
  'Sub Category Revenue Target [Prev Q]': 'aaogfQIve1tq',
  'Sub Category Revenue Target [QoQ[': 'aaygfem3gUaQ',
  'Sub Category Revenue Target [SUM]': 'aabgfvFua3wG',
  'Tender Type': 'label.storesalesfact.vendortype',
  'Test - Expected Sales': 'aazVDeStgmTk',
  'Test of Brand $ Market Share %': 'aaL8PqiOfZMV',
  Title: 'label.customerdimension.title',
  'Total Activewear Customer [COUNT]': 'aaGwyiuxaRjO',
  'Total Customer W BRAND [COUNT]': 'aaFwETyScFFW',
  'Total Customers [COUNT]': 'aahgsd82eElE',
  'Total Customers Online Sales [COUNT]': 'aanwRduOgojV',
  'Total Loyalty Customers [COUNT]': 'aaugrelAgnyn',
  'Total Order Cost': 'fact.storeordersfact.totalordercost',
  'Total Orders': 'abOfhp9DfKJo',
  'Total Orders Activewear': 'aadf2c0Pdwau',
  'Total Product [Count]': 'aaqJfW2Wd8vR',
  'Total Purchase Value': 'fact.customerfact.totalpurchasevalue',
  'Total Quantity [SUM]': 'aaLdJOyFfjUE',
  'Total Quantity W/O PF [SUM]': 'aaAwlpQPfTR7',
  'Total Revenue - Budget Conscious': 'aaslJQg4b755',
  'Total Revenue - Elite/Fashion Sports': 'abplL0Bvdxvg',
  'Total Revenue - Everyday Wearers': 'aaYlI0PMhqIR',
  'Total Revenue - Sporty': 'aahlKo1nbTjb',
  'Total Revenue [Prev Q]': 'ack9NTsEhl9l',
  'Total Revenue [Prev Y]': 'aacggFfibk22',
  'Total Revenue [QoQ]': 'acf9OVH3hFLU',
  'Total Revenue [SUM]': 'aaV9QfkKcQCL',
  'Total Revenue [SUM] Activewear': 'aauf0D7Ya1t1',
  'Total Revenue PO (Period Change)': 'aaIqqVv8bWq1',
  'Total Revenue PO [P Season]': 'abIqgBAUhFgV',
  'Total Revenue PO [SUM]': 'aagqiiqYh83N',
  'Total Sales [P Season]': 'aawrRLvNfoLy',
  'Total Sales Purchase (Period Change)': 'actrPsA8ih96',
  'Total Square Footage': 'label.storedimension.totalsquarefootage',
  'Transaction Type 1': 'label.onlinesalesfact.transactiontype',
  'Transaction Type 2': 'label.storesalesfact.transactiontype',
  'Trend Image': 'label.productdimension.trendimage',
  'Trend Market Share %': 'acordnjdgwPm',
  Trends: 'label.productdimension.trends',
  'Unit Price': 'fact.storeordersfact.unitprice',
  'Vendor Address': 'label.venderdimension.vendoraddress',
  'Vendor City': 'label.venderdimension.vendorcity',
  'Vendor Key': 'label.venderdimension.venderkey',
  'Vendor Name': 'label.venderdimension.vendorname',
  'Vendor Region': 'label.venderdimension.vendorregion',
  'Vendor State': 'label.venderdimension.endorstate',
  Weight: 'label.productdimension.weight',
  'Weight Units of Measure': 'label.productdimension.weightunitsofmeasure',
  'Year (Customer Since)': 'customersince.aag81lMifn6q',
  'Week (Sun-Sat)/Year (Customer Since)': 'customersince.aaA81lMifn6q',
  'Quarter/Year (Customer Since)': 'customersince.aci81lMifn6q',
  'Month/Year (Customer Since)': 'customersince.act81lMifn6q',
  'Date (Customer Since)': 'customersince.date.mmddyyyy',
  'Date (Customer Since) DataSet': 'customersince.dataset.dt',
  'Year (Date Delivered)': 'datedelivered.aag81lMifn6q',
  'Week (Sun-Sat)/Year (Date Delivered)': 'datedelivered.aaA81lMifn6q',
  'Quarter/Year (Date Delivered)': 'datedelivered.aci81lMifn6q',
  'Month/Year (Date Delivered)': 'datedelivered.act81lMifn6q',
  'Date (Date Delivered)': 'datedelivered.date.mmddyyyy',
  'Date (Date Delivered) DataSet': 'datedelivered.dataset.dt',
  'Year (Date Ordered)': 'dateordered.aag81lMifn6q',
  'Week (Sun-Sat)/Year (Date Ordered)': 'dateordered.aaA81lMifn6q',
  'Quarter/Year (Date Ordered)': 'dateordered.aci81lMifn6q',
  'Month/Year (Date Ordered)': 'dateordered.act81lMifn6q',
  'Date (Date Ordered)': 'dateordered.date.mmddyyyy',
  'Date (Date Ordered) DataSet': 'dateordered.dataset.dt',
  'Year (Date Shipped)': 'dateshipped.aag81lMifn6q',
  'Week (Sun-Sat)/Year (Date Shipped)': 'dateshipped.aaA81lMifn6q',
  'Quarter/Year (Date Shipped)': 'dateshipped.aci81lMifn6q',
  'Month/Year (Date Shipped)': 'dateshipped.act81lMifn6q',
  'Date (Date Shipped)': 'dateshipped.date.mmddyyyy',
  'Date (Date Shipped) DataSet': 'dateshipped.dataset.dt',
  'Year (Expected Delivery Date)': 'expecteddeliverydate.aag81lMifn6q',
  'Week (Sun-Sat)/Year (Expected Delivery Date)': 'expecteddeliverydate.aaA81lMifn6q',
  'Quarter/Year (Expected Delivery Date)': 'expecteddeliverydate.aci81lMifn6q',
  'Month/Year (Expected Delivery Date)': 'expecteddeliverydate.act81lMifn6q',
  'Date (Expected Delivery Date)': 'expecteddeliverydate.date.mmddyyyy',
  'Date (Expected Delivery Date) DataSet': 'expecteddeliverydate.dataset.dt',
  'Year (First Open Date)': 'firstopendate.aag81lMifn6q',
  'Week (Sun-Sat)/Year (First Open Date)': 'firstopendate.aaA81lMifn6q',
  'Quarter/Year (First Open Date)': 'firstopendate.aci81lMifn6q',
  'Month/Year (First Open Date)': 'firstopendate.act81lMifn6q',
  'Date (First Open Date)': 'firstopendate.date.mmddyyyy',
  'Date (First Open Date) DataSet': 'firstopendate.dataset.dt',
  'Year (Last Deal Update) 1': 'lastdealupdate.aag81lMifn6q',
  'Year (Last Deal Update) 2': 'lastdealupdate1.aag81lMifn6q',
  'Week (Sun-Sat)/Year (Last Deal Update) 1': 'lastdealupdate.aaA81lMifn6q',
  'Week (Sun-Sat)/Year (Last Deal Update) 2': 'lastdealupdate1.aaA81lMifn6q',
  'Quarter/Year (Last Deal Update) 1': 'lastdealupdate.aci81lMifn6q',
  'Quarter/Year (Last Deal Update) 2': 'lastdealupdate1.aci81lMifn6q',
  'Month/Year (Last Deal Update) 1': 'lastdealupdate.act81lMifn6q',
  'Month/Year (Last Deal Update) 2': 'lastdealupdate1.act81lMifn6q',
  'Date (Last Deal Update) 1': 'lastdealupdate.date.mmddyyyy',
  'Date (Last Deal Update) 2': 'lastdealupdate1.date.mmddyyyy',
  'Date (Last Deal Update) DataSet 1': 'lastdealupdate.dataset.dt',
  'Date (Last Deal Update) DataSet 2': 'lastdealupdate1.dataset.dt',
  'Year (Last Remodel Date)': 'lastremodeldate.aag81lMifn6q',
  'Week (Sun-Sat)/Year (Last Remodel Date)': 'lastremodeldate.aaA81lMifn6q',
  'Quarter/Year (Last Remodel Date)': 'lastremodeldate.aci81lMifn6q',
  'Month/Year (Last Remodel Date)': 'lastremodeldate.act81lMifn6q',
  'Date (Last Remodel Date)': 'lastremodeldate.date.mmddyyyy',
  'Date (Last Remodel Date) DataSet': 'lastremodeldate.dataset.dt',
  'Year (Promotion Begin Date)': 'promotionbegindate.aag81lMifn6q',
  'Week (Sun-Sat)/Year (Promotion Begin Date)': 'promotionbegindate.aaA81lMifn6q',
  'Quarter/Year (Promotion Begin Date)': 'promotionbegindate.aci81lMifn6q',
  'Month/Year (Promotion Begin Date)': 'promotionbegindate.act81lMifn6q',
  'Date (Promotion Begin Date)': 'promotionbegindate.date.mmddyyyy',
  'Date (Promotion Begin Date) DataSet': 'promotionbegindate.dataset.dt',
  'Year (Promotion End Date)': 'promotionenddate.aag81lMifn6q',
  'Week (Sun-Sat)/Year (Promotion End Date)': 'promotionenddate.aaA81lMifn6q',
  'Quarter/Year (Promotion End Date)': 'promotionenddate.aci81lMifn6q',
  'Month/Year (Promotion End Date)': 'promotionenddate.act81lMifn6q',
  'Date (Promotion End Date)': 'promotionenddate.date.mmddyyyy',
  'Date (Promotion End Date) DataSet': 'promotionenddate.dataset.dt',
  'Year (Sales Date)': 'salesdate.aag81lMifn6q',
  'Week (Sun-Sat)/Year (Sales Date)': 'salesdate.aaA81lMifn6q',
  'Quarter/Year (Sales Date)': 'salesdate.aci81lMifn6q',
  'Month/Year (Sales Date)': 'salesdate.act81lMifn6q',
  'Date (Sales Date)': 'salesdate.date.mmddyyyy',
  'Date (Sales Date) DataSet': 'salesdate.dataset.dt' }
